# Generated by Django 4.2.16 on 2024-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField(max_length=10)),
                ('user_profile_pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
