# Generated by Django 4.2.16 on 2024-10-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='user_phone',
            field=models.CharField(max_length=10),
        ),
    ]
